### ISSUE TITLE
Permission problems with volumes mounted in docker-compose file

### ISSUE THREAD

**Issue by carlosnatalino** [autolab/docker#12]
Hi,

I am currently using the docker-compose file provided in this repository, and I could see that when I run `docker-compose up` and try to access the service in the browser, I get an error message like the figure below:

![Screenshot 2020-10-23 at 15 08 21](https://user-images.githubusercontent.com/6130746/97007428-acbc2100-1541-11eb-8f00-fc3cdb533066.png)

When I investigate further, I can see that the output of the autolab container is as follows:

```
autolab    | App 124 output: Using /usr/local/rvm/gems/ruby-2.6.6
autolab    | App 124 output: Error: The application encountered the following error: cannot load such file -- /home/app/webapp/config/environments/production.rb (LoadError)
autolab    | App 124 output:     /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
autolab    | App 124 output:     /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
autolab    | App 124 output:     /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
autolab    | App 124 output:     /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
```

I checked and the file `config/environments/production.rb` is in the correct folder. So, I looked at the permissions in the /home/app/webapp, and they are as follows:

```
root@37329f872158:/home/app/webapp# ls -la
total 200
drwxr-xr-x 1 app  app   4096 Oct 23 02:37 .
drwxr-xr-x 1 app  app   4096 Oct 22 12:30 ..
drwx------ 1 app  app   4096 Oct 22 12:08 app
drwx------ 1 app  app   4096 Oct 22 12:08 bin
drwx------ 1 app  app   4096 Oct 22 12:09 config
-rwx------ 1 app  app    158 Oct 22 12:08 config.ru
-rw------- 1 app  app  32198 Oct 22 12:08 config.zip
-rw------- 1 app  app   6449 Oct 22 12:08 CONTRIBUTING.md
drwxr-xr-x 2 root root  4096 Oct 22 12:34 courses          <-- volume
drwx------ 3 1001 1001  4096 Oct 23 02:32 db          <-- volume
drwx------ 1 app  app   4096 Oct 22 12:09 docker
-rw------- 1 app  app   1418 Oct 22 12:09 Dockerfile
-rw------- 1 app  app      6 Oct 22 12:08 .dockerignore
drwx------ 1 app  app   4096 Oct 22 12:09 docs
drwx------ 1 app  app   4096 Oct 22 12:08 examples
-rw------- 1 app  app   3415 Oct 22 12:08 Gemfile
-rw------- 1 app  app   9482 Oct 22 12:09 Gemfile.lock
drwx------ 1 app  app   4096 Oct 22 12:08 .github
-rw------- 1 app  app    734 Oct 22 12:09 .gitignore
drwx------ 1 app  app   4096 Oct 22 12:08 lib
-rw------- 1 app  app  11324 Oct 22 12:08 LICENSE
drwxr-xr-x 1 app  app   4096 Oct 23 02:37 log
-rw------- 1 app  app   1227 Oct 22 12:09 mkdocs.yml
drwx------ 1 app  app   4096 Oct 23 02:37 public
-rwx------ 1 app  app    273 Oct 22 12:08 Rakefile
-rw------- 1 app  app    604 Oct 22 12:08 .rake_tasks~
-rw------- 1 app  app   5585 Oct 22 12:09 README.md
-rw------- 1 app  app     81 Oct 22 12:08 .rspec
-rw------- 1 app  app   4592 Oct 22 12:08 .rubocop_todo.yml
-rw------- 1 app  app    873 Oct 22 12:08 .rubocop.yml
-rw------- 1 app  app      6 Oct 22 12:08 .ruby-version
drwx------ 1 app  app   4096 Oct 22 12:08 script
drwx------ 1 app  app   4096 Oct 22 12:08 spec
drwx------ 1 app  app   4096 Oct 22 12:08 templates
drwxrwxr-x 3 app  app   4096 Oct 23 02:37 tmp
-rw------- 1 app  app   1658 Oct 22 12:08 .travis.yml
```

The files within `config` are:

```
root@37329f872158:/home/app/webapp# ls -la config
total 108
drwx------ 1 app  app  4096 Oct 22 12:09 .
drwxr-xr-x 1 app  app  4096 Oct 23 02:37 ..
-rwx------ 1 app  app  5414 Oct 22 12:08 application.rb
-rwx------ 1 1001 1001  699 Oct 22 12:09 autogradeConfig.rb          <-- volume
-rwx------ 1 app  app   699 Oct 22 12:08 autogradeConfig.rb.template
-rwx------ 1 app  app   128 Oct 22 12:08 boot.rb
-rw------- 1 app  app   116 Oct 22 12:08 cable.yml
-rw------- 1 app  app   201 Oct 22 12:09 database.docker.yml
-rwx------ 1 app  app   667 Oct 22 12:08 database.travis.yml
-rw------- 1 1001 1001  201 Oct 22 12:09 database.yml          <-- volume
-rwx------ 1 app  app   488 Oct 22 12:08 database.yml.template
-rwx------ 1 app  app   128 Oct 22 12:08 environment.rb
drwx------ 1 app  app  4096 Oct 22 12:09 environments
drwx------ 1 app  app  4096 Oct 22 12:36 initializers
drwx------ 1 app  app  4096 Oct 22 12:08 locales
-rw------- 1 app  app  9693 Oct 22 12:08 newrelic.yml
-rwx------ 1 app  app    46 Oct 22 12:08 preinitializer.rb
-rw------- 1 app  app  2005 Oct 22 12:08 puma.rb
-rwx------ 1 app  app  5096 Oct 22 12:08 routes.rb
-rw------- 1 app  app   473 Oct 22 12:09 school.yml
-rw------- 1 app  app   473 Oct 22 12:08 school.yml.template
-rw------- 1 app  app   965 Oct 22 12:08 secrets.yml
-rw------- 1 app  app   111 Oct 22 12:08 spring.rb
```

What we observe is that all the files mounted as volumes by the `docker-compose.yml` file have different permissions, which make them inaccessible by the application.

I noticed that all these files are copied to the container in the ./Autolab/Dockerfile, but they are again mounted by the `docker-compose.yml`.

I could solve the issue by removing lines 31-36 of the `docker-compose.yml` file and running `docker-compose build` again. Then, autolab runs correctly after `docker-compose up`.

Since there is a comment stating that these volumes should be explicit, I didn't submit a PR, but I'd like to make you aware of this.

**Comment by fanpu** [comment]
Thanks for reporting this issue! I will fix this by updating the Makefile to also set the correct user:group information for the files, in addition to creating the courses directory explicitly
