### ISSUE TITLE
Tango autograding issues

### ISSUE THREAD

**Issue by fanpu** [autolab/docker#26]
Seems like the feedback file (`'/opt/TangoService/Tango/volumes/prod-1000-autograding_image/feedback'`) was not found

```
DEBUG|2020-12-03 21:36:21,883|JobQueue|assignJob| Acquired lock to job queue.
DEBUG|2020-12-03 21:36:21,883|JobQueue|assignJob| Retrieved job.
INFO|2020-12-03 21:36:21,883|JobQueue|assignJob|Assigning job ID: 2
DEBUG|2020-12-03 21:36:21,884|JobQueue|assignJob| Releasing lock to job queue.
DEBUG|2020-12-03 21:36:21,884|JobQueue|assignJob| Released lock to job queue.
INFO|2020-12-03 21:36:21,884|JobManager|Dispatched job 15-213_hello_2_fzeng@andrew.cmu.edu:2 to autograding_image [try 0]
DEBUG|2020-12-03 21:36:21,921|Worker|Run worker
DEBUG|2020-12-03 21:36:21,923|Worker|Assigning job to preallocated VM
INFO|2020-12-03 21:36:21,923|Worker|Assigned job 15-213_hello_2_fzeng@andrew.cmu.edu:2 existing VM prod-1000-autograding_image
DEBUG|2020-12-03 21:36:21,924|Worker|Assigned job to preallocated VM
DEBUG|2020-12-03 21:36:21,924|Worker|Job 15-213_hello_2_fzeng@andrew.cmu.edu:2 waiting for VM prod-1000-autograding_image
DEBUG|2020-12-03 21:36:21,924|Worker|Waiting for VM
DEBUG|2020-12-03 21:36:21,924|Worker|Waited for VM
INFO|2020-12-03 21:36:21,924|Worker|VM prod-1000-autograding_image ready for job 15-213_hello_2_fzeng@andrew.cmu.edu:2
DEBUG|2020-12-03 21:36:21,962|LocalDocker|Copied in file courselabs/REPLACE_ME_SECRET_TANGO_KEY-15-213-hello/fzeng@andrew.cmu.edu_2_hello.c to /opt/TangoService/Tango/volumes/prod-1000-autograding_image/hello.c
DEBUG|2020-12-03 21:36:21,963|LocalDocker|Copied in file courselabs/REPLACE_ME_SECRET_TANGO_KEY-15-213-hello/autograde-Makefile to /opt/TangoService/Tango/volumes/prod-1000-autograding_image/Makefile
DEBUG|2020-12-03 21:36:21,963|LocalDocker|Copied in file courselabs/REPLACE_ME_SECRET_TANGO_KEY-15-213-hello/autograde.tar to /opt/TangoService/Tango/volumes/prod-1000-autograding_image/autograde.tar
INFO|2020-12-03 21:36:21,963|Worker|Input copied for job 15-213_hello_2_fzeng@andrew.cmu.edu:2 [status=0]
DEBUG|2020-12-03 21:36:21,964|LocalDocker|Running job: ['docker', 'run', '--name', 'prod-1000-autograding_image', '-v', '/opt/TangoService/Tango/volumes/prod-1000-autograding_image/:/home/mount', 'autograding_image', 'sh', '-c', 'cp -r mount/* autolab/; su autolab -c "autodriver -u 100 -f 104857600 -t 180 -o 1024000 autolab > output/feedback 2>&1";                         cp output/feedback mount/feedback']
DEBUG|2020-12-03 21:36:31,114|LocalDocker|runJob returning 0
INFO|2020-12-03 21:36:31,114|Worker|Job 15-213_hello_2_fzeng@andrew.cmu.edu:2 executed [status=0]
ERROR|2020-12-03 21:36:31,382|Worker|Internal Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/TangoService/Tango/volumes/prod-1000-autograding_image/feedback' -> 'courselabs/REPLACE_ME_SECRET_TANGO_KEY-15-213-hello/output/fzeng@andrew.cmu.edu_2_hello_autograde.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/TangoService/Tango/worker.py", line 277, in run
    ret["copyout"] = self.vmms.copyOut(vm, self.job.outputFile)
  File "/opt/TangoService/Tango/vmms/localDocker.py", line 165, in copyOut
    shutil.move(volumePath + 'feedback', destFile)
  File "/usr/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/TangoService/Tango/volumes/prod-1000-autograding_image/feedback'
INFO|2020-12-03 21:36:32,616|Preallocator|createVM|calling initializeVM
INFO|2020-12-03 21:36:32,616|Preallocator|createVM|done with initializeVM
DEBUG|2020-12-03 21:36:32,618|Preallocator|createVM: Added vm 1002 to pool autograding_image
```

**Comment by fanpu** [comment]
Found the bug. When Tango is running a Docker container for its autograding job, because of the fact that we are mapping the sockets to the Tango container this causes the mount point to actually be with respect to the host instead of the Tango container itself.

**Comment by fanpu** [comment]
Example of running a job with localDocker: 
`docker run --name prod-1002-autograding_image -v /opt/TangoService/Tango/volumes/prod-1002-autograding_image/:/home/mount autograding_image sh -c cp -r mount/* autolab/; su autolab -c "autodriver -u 100 -f 104857600 -t 60 -o 1024000 autolab > output/feedback 2>&1"; cp output/feedback mount/feedback`

Here we see that the job itself also tries to perform a volume mapping.

**Comment by fanpu** [comment]
Fixed by https://github.com/autolab/docker/pull/28
